### ISSUE TITLE
How to install on Catalina?

### ISSUE THREAD

**Issue by orschiro** [mutsune/SSIDonMenubar#1]
Hi @mutsune, 

I would love to use this on Catalina!

How do I install it?

**Comment by mutsune** [comment]
Hi @orschiro,

You can use SSIDonMenubar on Catalina since I've just migrated the code to Swift 5. 😉 #2
If you can use Xcode, open `SSIDonMenubar.xcodeproj` and build, then you will get `SSIDonMenubar.app`.

**Comment by orschiro** [comment]
Thank you! :)

**Comment by mutsune** [comment]
@orschiro Now you can download the built app from [releases](https://github.com/mutsune/SSIDonMenubar/releases/tag/v1.0.0)!

**Comment by orschiro** [comment]
This is even better. Thank you so much!
