### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by orschiro** [mutsune/SSIDonMenubar#9]
Hi @mutsune ,

My wifi is called TP-Link_7FB6 but your app only shows me TP-

Any idea why?

Thank you!

**Comment by mutsune** [comment]
@orschiro 
As it says in the README, SSIDonMenubar shows only 3 characters.
I don't use this tool actually and have no plans to improve that limitation, but you can rewrite the following line and rebuild them on your PC.

https://github.com/mutsune/SSIDonMenubar/blob/da937952488c4fc8387453798bcda9ae17137abc/SSIDonMenubar/AppDelegate.swift#L32

There are many similar tools available. For example:
https://github.com/matryer/bitbar-plugins/blob/master/Network/wifiname.sh
(I like [bitbar](https://github.com/matryer/bitbar) but it hasn't been maintenance recently😢)

Thanks

**Comment by mutsune** [comment]
When I first made this tool, I didn't think anyone would use it, so I'm glad some people are using it 🙂

**Comment by orschiro** [comment]
Ah, have overlooked the README, thanks! :-)
